[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

